### PR TITLE
PNDA-1899: Scala Spark Jupyter Integration

### PR DESCRIPTION
**Pull request by mrunmayeejog**
# Problem Statement:
PNDA-1899: Scala Spark Jupyter Integration

# Analysis:
Scala support for Spark coding is provided by adding two new kernels along with other kernels in Jupyter notebook - 
1. Scala kernel is added for standalone Scala programming.
2. Spark kernel is added by installing Sparkmagic and Apache livy. Sparkmagic facilitates interaction with remote Spark cluster through Livy. Apache livy is a RESTful service that enables this interation with remote Spark cluster.

# Changes:
For Scala Spark Jupyter Integration, package dependencies for both scala kernel and spark kernels are added. Scala kernel and Livy packages are added to the mirror server in static dependency file. Sparkmagic and its required dependencies are added to python requirements.

### CODE REVIEW

**Comment by trsmith2** [comment]
A few questions/comments on the code -
- Could you briefly explain the need to introduce Kerberos?
- The Apache download location for Livy looks suspect - please use official CDNs rather than local mirrors that are likely to change
- Is there an official build of jupyter-scala that can be referenced rather than the SNAPSHOT version used here?

**Comment by mrunmayeejog** [comment]
Please find comments:
1.  As per the requirement specifications of sparkmagic, its dependencies include request_kerberos which internally required pykerberos. Hence pykerberos and its required package dependencies were introduced.
2. Looking into it. Will test with new livy downloads and get back to you on this.
3. Jupyter-scala build is available and it worked for online deployment mode. However we faced issues in case of offline mode. The build uses coursier which is a package dependency resolver which looks for packages in online repos. We tried configuring it for offline mode but dependencies increased. Hence using current SNAPSHOT mirror which provides all the required dependencies.

**Comment by trsmith2** [comment]
The issue is that SNAPSHOTs are exactly that: snapshots that aren't guaranteed to remain the same over time.

What is the corresponding release this depends on and what are the dependencies that are missing/problematic?

**Comment by willis27** [comment]
Regarding to livy download, why we need download another livy service? HDP and CDH both come with livy service?

**Comment by mrunmayeejog** [comment]
For livy download, I found livy services available for HDP. However I did not find them in CDH distribution. For both distributions checked into /usr/hdp/ and /opt/cloudera folders respectively. So I will need to download another livy service for CDH distribution.

**Comment by mrunmayeejog** [comment]
Closing PR for PNDA-1899 as working on required modifcations. Will raise new PR post testing.

**Pull request closed without merging**
